/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/reservables/": {
    /** Get Reservables */
    get: operations["reservation_reservables_controller_get_reservables"];
  };
  "/api/reservation/": {
    /** Get Reservables */
    get: operations["reservation_reservation_controller_get_reservables"];
  };
  "/api/auth/login/": {
    /**
     * Post Login
     * @description This is a function to login a user.
     *
     * When a user is logged in, a token is created.
     *
     * :param username: The username of the user.
     *
     * :param password: The password of the user.
     *
     * :return token: The token of the user.
     *
     * :return exp: The time when the token expires in epoch
     */
    post: operations["authentication_authsession_controller_post_login"];
  };
  "/api/auth/logout/": {
    /**
     * Post Logout
     * @description This is a function to logout a user.
     *
     * When a user is logged out all the auth sessions are deleted.
     *
     * :param token: The token of the user.
     *
     * :return: True if the user is logged out.
     */
    post: operations["authentication_authsession_controller_post_logout"];
  };
  "/api/auth/validate-session/": {
    /**
     * Post Validate Session
     * @description     Check if the session is valid using token.
     *
     *     checking will not refresh session expiry time.
     * .
     */
    get: operations["authentication_authsession_controller_post_validate_session"];
  };
  "/api/register/": {
    /**
     * Register
     * @description This is a function to register a user.
     *
     * :param username: The username of the user.
     *
     * :param password: The password of the user.
     *
     * :param email: The email of the user.
     *
     * :param first_name: The first name of the user.
     *
     * :param last_name: The last name of the user.
     *
     * :return: The user that is created.
     */
    post: operations["authentication_user_controller_register"];
  };
  "/api/me/": {
    /**
     * Me
     * @description This is a function to get the current user.
     *
     * :return: The current user.
     */
    get: operations["authentication_user_controller_me"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** ReservableSchema */
    ReservableSchema: {
      /** ID */
      id?: number | null;
      /** Name */
      name: string;
      /**
       * Capacity
       * @default 1
       */
      capacity?: number;
      /**
       * Location
       * @default
       */
      location?: string;
      /**
       * Description
       * @default
       */
      description?: string;
      /** Image */
      image?: string | null;
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean;
    };
    /** ReservationSchema */
    ReservationSchema: {
      /** ID */
      id?: number | null;
      /** User */
      user: number;
      /** Reservable */
      reservable: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Start Time
       * Format: date-time
       */
      start_time: string;
      /**
       * End Time
       * Format: date-time
       */
      end_time: string;
    };
    /** LoginPostOut */
    LoginPostOut: {
      /** Token */
      token: string;
      /** Exp */
      exp: number;
    };
    /** LoginPostIn */
    LoginPostIn: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** ValidateSessionPostOut */
    ValidateSessionPostOut: {
      /** Is Valid */
      is_valid: boolean;
    };
    /** UserSchemaOut */
    UserSchemaOut: {
      /** Id */
      id: number;
      /** Username */
      username: string;
      /** Email */
      email: string;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
    };
    /** UserSchemaIn */
    UserSchemaIn: {
      /** Username */
      username: string;
      /** Password */
      password: string;
      /** Email */
      email: string;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get Reservables */
  reservation_reservables_controller_get_reservables: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ReservableSchema"][];
        };
      };
    };
  };
  /** Get Reservables */
  reservation_reservation_controller_get_reservables: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ReservationSchema"][];
        };
      };
    };
  };
  /**
   * Post Login
   * @description This is a function to login a user.
   *
   * When a user is logged in, a token is created.
   *
   * :param username: The username of the user.
   *
   * :param password: The password of the user.
   *
   * :return token: The token of the user.
   *
   * :return exp: The time when the token expires in epoch
   */
  authentication_authsession_controller_post_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginPostIn"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["LoginPostOut"];
        };
      };
    };
  };
  /**
   * Post Logout
   * @description This is a function to logout a user.
   *
   * When a user is logged out all the auth sessions are deleted.
   *
   * :param token: The token of the user.
   *
   * :return: True if the user is logged out.
   */
  authentication_authsession_controller_post_logout: {
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
    };
  };
  /**
   * Post Validate Session
   * @description     Check if the session is valid using token.
   *
   *     checking will not refresh session expiry time.
   * .
   */
  authentication_authsession_controller_post_validate_session: {
    parameters: {
      query: {
        token: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ValidateSessionPostOut"];
        };
      };
    };
  };
  /**
   * Register
   * @description This is a function to register a user.
   *
   * :param username: The username of the user.
   *
   * :param password: The password of the user.
   *
   * :param email: The email of the user.
   *
   * :param first_name: The first name of the user.
   *
   * :param last_name: The last name of the user.
   *
   * :return: The user that is created.
   */
  authentication_user_controller_register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserSchemaIn"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["UserSchemaOut"];
        };
      };
    };
  };
  /**
   * Me
   * @description This is a function to get the current user.
   *
   * :return: The current user.
   */
  authentication_user_controller_me: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["UserSchemaOut"];
        };
      };
    };
  };
}
